server:
  port: 8099

spring:
  application:
    name: spring-oauth
  datasource:
    url: jdbc:mysql://oauth-mysql:33064?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
    username: "root"
    password: "root1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: spring-oauth-pool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000         # 10분
      max-lifetime: 1800000        # 30분
      connection-timeout: 30000    # 30초
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: create       # create, create-drop, update, validate, none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        highlight_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          kakao:
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            client-name: kakao
            scope: profile_nickname, profile_image
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          naver:
            client-id: ${naver_client_id}
            client-secret: ${naver_client_secret}
            client-name: naver
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope: name, email, profile_image
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG